apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-container-deployment
spec:
  selector:
    matchLabels:
      app: news-container
  replicas: 1
  template:
    metadata:
      labels:
        app: news-container
    spec:
      containers:
        - image: "utkarsha20/news-container"
          imagePullPolicy: Always
          name: news-container
          ports:
            - containerPort: 8081
          resources:
            limits:
                cpu: 500m
            requests:
                cpu: 200m