apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-container-deployment
spec:
  selector:
    matchLabels:
      app: weather-container
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-container
    spec:
      containers:
        - image: "utkarsha20/weather-container"
          imagePullPolicy: Always
          name: weather-container
          ports:
            - containerPort: 8082
          resources:
            limits:
                cpu: 500m
            requests:
                cpu: 200m